# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import galleries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('front_view', models.BooleanField(default=False)),
                ('date_build', models.DateField()),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, null=True, quality=90, size=[1280, 720], upload_to=galleries.models.image_folder)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-date_build'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='buildingimages',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Location'),
        ),
    ]
