# Generated by Django 2.0 on 2017-12-17 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingimages',
            options={'ordering': ['-build_date']},
        ),
        migrations.RemoveField(
            model_name='buildingimages',
            name='date_build',
        ),
        migrations.AddField(
            model_name='buildingimages',
            name='build_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
