# Generated by Django 2.0 on 2017-12-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20171216_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingimages',
            options={'ordering': ['-date_build']},
        ),
        migrations.RenameField(
            model_name='buildingimages',
            old_name='build_date',
            new_name='date_build',
        ),
    ]
