# Generated by Django 2.0 on 2017-12-17 12:04

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20171216_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingimages',
            name='thumb_image',
            field=models.ImageField(default=2, editable=False, upload_to=galleries.models.image_folder),
            preserve_default=False,
        ),
    ]
