# Generated by Django 2.0 on 2017-12-17 12:04

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_buildingimages_thumb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimages',
            name='thumb_image',
            field=models.ImageField(blank=True, editable=False, upload_to=galleries.models.image_folder),
        ),
    ]
