# Generated by Django 2.0 on 2017-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20171217_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingimages',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buildingimages',
            name='date_build',
            field=models.DateField(blank=True, editable=False),
        ),
    ]
