# Generated by Django 2.0 on 2017-12-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_auto_20171217_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('metakey', models.TextField(blank=True, default=None)),
                ('metadesc', models.TextField(blank=True, default=None)),
                ('metadata', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='buildingimages',
            name='front_view',
        ),
        migrations.AddField(
            model_name='buildingimages',
            name='imgorigsize',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingimages',
            name='metadata',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingimages',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingimages',
            name='category',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='galleries.Category'),
            preserve_default=False,
        ),
    ]
