# Generated by Django 2.0 on 2017-12-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0008_auto_20171217_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
