# Generated by Django 2.0 on 2017-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0010_auto_20171217_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimages',
            name='imgorigsize',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='buildingimages',
            name='metadata',
            field=models.TextField(editable=False),
        ),
    ]
