# Generated by Django 2.0 on 2017-12-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0011_auto_20171217_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimages',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, unique=True),
        ),
    ]
