# Generated by Django 2.0 on 2017-12-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0012_auto_20171217_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingimages',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='category',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='category',
            name='metadesc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='metakey',
        ),
    ]
